apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
stringData:
  MONGO_VIDEOS: "mongodb+srv://<username>:<password>@sandbox.d0qrl.mongodb.net/videos?retryWrites=true&w=majority"
  MONGO_MP3S: "mongodb+srv://<username>:<password>@sandbox.d0qrl.mongodb.net/mp3s?retryWrites=true&w=majority"
type: Opaque